const CATALOG = [
	{
		id: 'el1',
		name: 'FENDER SQUIER MM STRATOCASTER HARD TAIL BLACK',
		img: 'img/catalog/el1.jpg',
		price: 13600,
	},
	{
		id: 'el2',
		name: 'FENDER SQUIER MM STRATOCASTER HARD TAIL RED',
		img: 'img/catalog/el2.jpg',
		price: 13600,
	},
	{
		id: 'el3',
		name: 'SOLAR GUITARS A2.6C ЭЛЕКТРОГИТАРА, ЦВЕТ ЧЁРТНЫЙ МАТОВЫЙ',
		img: 'img/catalog/el3.jpg',
		price: 71000,
	},
	{
		id: 'el4',
		name: 'GIBSON 2019 LES PAUL TRIBUTE SATIN CHERRY SUNBURST',
		img: 'img/catalog/el4.jpg',
		price: 140000,
	},
	{
		id: 'el5',
		name: 'IBANEZ S520-WK',
		img: 'img/catalog/el5.jpg',
		price: 60000,
	},
	{
		id: 'el6',
		name: 'IBANEZ RGA42FM-BLF',
		img: 'img/catalog/el6.jpg',
		price: 47000,
	},
	{
		id: 'el7',
		name: 'IBANEZ RG8-WH 8-STRING RG',
		img: 'img/catalog/el7.jpg',
		price: 55000,
	},
	{
		id: 'el8',
		name: 'IIBANEZ RG421-MOL',
		img: 'img/catalog/el8.jpg',
		price: 41000,
	},
	{
		id: 'el9',
		name: 'JACKSON JS22-7 DKA, AH FB - HT STN BLK',
		img: 'img/catalog/el9.jpg',
		price: 36000,
	},
	{
		id: 'el10',
		name: 'GIBSON 2019 EXPLORER ANTIQUE NATURAL',
		img: 'img/catalog/el10.jpg',
		price: 202000,
	},
	{
		id: 'el11',
		name: 'RGA42EX-BAM',
		img: 'img/catalog/el11.jpg',
		price: 47000,
	},
	{
		id: 'el12',
		name: 'GIBSON 2019 SG TRIBUTE VINTAGE CHERRY SATIN',
		img: 'img/catalog/el12.jpg',
		price: 128000,
	},
	{
		id: 'el13',
		name: 'EPIPHONE SG MODERN FIGURED TRANS BLACK FADE',
		img: 'img/catalog/el13.jpg',
		price: 67000,
	},
	{
		id: 'el14',
		name: 'RG421PB-CHF',
		img: 'img/catalog/el14.jpg',
		price: 50000,
	},
	{
		id: 'el15',
		name: 'GIBSON 2019 LES PAUL STUDIO EBONY',
		img: 'img/catalog/el15.jpg',
		price: 170000,
	},
	{
		id: 'el16',
		name: 'GIBSON LES PAUL SPECIAL TRIBUTE HUMBUCKER VINTAGE CHERRY SATIN',
		img: 'img/catalog/el16.jpg',
		price: 107000,
	},
	{
		id: 'el17',
		name: 'SOLAR GUITARS A2.7C 7-СТРУННАЯ ГИТАРА, ЦВЕТ ЧЕРНЫЙ',
		img: 'img/catalog/el17.jpg',
		price: 73000,
	},
	{
		id: 'el18',
		name: 'GIBSON 2019 LES PAUL CLASSIC EBONY',
		img: 'img/catalog/el18.jpg',
		price: 215000,
	},
	{
		id: 'el19',
		name: 'IBANEZ S521-MOL MAHOGANY OIL',
		img: 'img/catalog/el19.jpg',
		price: 51000,
	},
	{
		id: 'el20',
		name: 'CORT X700-LBB DUALITY X SERIES',
		img: 'img/catalog/el20.jpg',
		price: 71000,
	},
	{
		id: 'el21',
		name: 'EPIPHONE ES-339 CHERRY',
		img: 'img/catalog/el21.jpg',
		price: 64000,
	},
	{
		id: 'el22',
		name: 'IBANEZ SA360NQM-BMG',
		img: 'img/catalog/el22.jpg',
		price: 52000,
	},
];